# Config for qualys-catalog-design
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

files:
  templates_folder: 
  output_folder: 
  output_file: 
  core_file: 
  application_file: 
base_urls:
  local:
    css: 
    logo: 
  stage:
    css: 
    logo: 
  production:
    css: 
    logo: 
