# Config for qualys-catalog-design
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

files:
  templates_folder: 
  output_folder: 
  output_file: 
  learning_paths:
    core_file: 
      title:
      file:
    application_file: 
      title:
      file:
base_urls:
  local:
    css: 
    background: 
    logo: 
      href:
      alt:
    levels_of_training:
      href: 
      alt: 
  stage:
    css: 
    background: 
    logo: 
      href:
      alt:
    levels_of_training:
      href: 
      alt: 
  production:
    css: 
    background: 
    logo: 
      href:
      alt:
    levels_of_training:
      href: 
      alt: 
